language: cpp

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -y libwxgtk3.0-dev cmake make g++-4.8

install:
  - export CXX="g++-4.8"
  - mkdir build
  - cd build
  - cmake ..
  - make
