language: cpp
dist: trusty
sudo: required

before_install:
  - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
  - sudo apt-get update -qq
  - sudo apt-get install -y libwxgtk3.0-dev cmake make g++
  - mkdir build

script:
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make -j2
